// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"jinx/src/jinkiesengine"
)

// Injectors from wire.go:

func initializeCobraJinkies() jinkiesengine.Jinkies {
	string2 := getContainerConfigPath()
	containerInfo := hydrateFromConfig(string2)
	jinkies := jinkiesengine.NewJinkies(containerInfo)
	return jinkies
}

// wire.go:

func getContainerConfigPath() string {
	return containerConfigPath
}
